"""Улучшение моделей: server_default, onupdate, lazy loading, индексы

Revision ID: 4e6debc855da
Revises: 450aefd42d81
Create Date: 2025-12-03 01:18:31.792496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e6debc855da'
down_revision: Union[str, None] = '450aefd42d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CUSTOMER', 'ADMIN', name='user_role'),
               type_=sa.Enum('CUSTOMER', 'ADMIN', name='user_role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CUSTOMER', 'ADMIN', name='user_role', native_enum=False),
               type_=postgresql.ENUM('CUSTOMER', 'ADMIN', name='user_role'),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    # ### end Alembic commands ###
